{"time":"2025-05-23T20:44:53.632293336Z","level":"INFO","msg":"stream: starting","core version":"0.19.11","symlink path":"/home/aaron/src/first-aid/demo/firstaid/notebooks/wandb/run-20250523_204453-2e2i6dkc/logs/debug-core.log"}
{"time":"2025-05-23T20:44:53.819762445Z","level":"INFO","msg":"created new stream","id":"2e2i6dkc"}
{"time":"2025-05-23T20:44:53.819813476Z","level":"INFO","msg":"stream: started","id":"2e2i6dkc"}
{"time":"2025-05-23T20:44:53.819826716Z","level":"INFO","msg":"writer: Do: started","stream_id":"2e2i6dkc"}
{"time":"2025-05-23T20:44:53.819860777Z","level":"INFO","msg":"handler: started","stream_id":"2e2i6dkc"}
{"time":"2025-05-23T20:44:53.819891428Z","level":"INFO","msg":"sender: started","stream_id":"2e2i6dkc"}
{"time":"2025-05-23T20:44:53.897756887Z","level":"ERROR","msg":"HTTP error","status":422,"method":"POST","url":"https://api.wandb.ai/graphql"}
{"time":"2025-05-23T20:44:53.897869859Z","level":"ERROR","msg":"sender: upsertRun:","error":"failed to upsert bucket: returned error 422: {\"data\":{\"upsertBucket\":null},\"errors\":[{\"message\":\"Error 3988 (HY000): Conversion from collation utf8mb4_0900_ai_ci into utf8mb3_general_ci impossible for parameter\",\"path\":[\"upsertBucket\"]}]}"}
